### ISSUE TITLE
Segfault on mississippixsissy$

### ISSUE THREAD

**Issue by tomsmeding** [Rerito/suffix-tree-v2#5]
The following code crashes reproducibly with a segmentation fault on my machine:

```
st::suffix_tree<> t1('$');
t1.emplace("mississippixsissy$");
```

This happens on the `master` branch. Since the crash doesn't occur when changing the string slightly, e.g. by removing the 'x', I'm tempted to think it's a bug in the algorithm.

Ukkonen's algorithm is a royal pain to implement, so thanks heaps for making this; I just wanted to let you know.

**Comment by Rerito** [comment]
Hi Tom,

This is indeed a bug in my implementation. I was able to reproduce it and developed a quick `print_tree` function to check my suffix trees' layout... Not one is correct...

Thank you for pointing it out!

**Comment by Rerito** [comment]
After a complete rework, it appears this issue is solved!
